[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node --max-old-space-size=200 --expose-gc src/index.js"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[[volumes]]
mountPath = "/data"

[healthcheck]
path = "/health"
initialDelaySeconds = 10
periodSeconds = 30
timeoutSeconds = 5
